apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-longhorn.fullname" . }}
  labels:
    {{- include "postgres-longhorn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "postgres-longhorn.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP

