apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-localpath.fullname" . }}
  labels:
    {{- include "postgres-localpath.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgres-localpath.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres-localpath.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-localpath.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "postgres-localpath.secretName" . }}
          env:
            - name: PGDATA
              value: {{ .Values.postgres.pgdata | quote }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "postgres-localpath.pvcName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
