all:
  children:
    nginx:
      hosts:
        nginx1:
          ansible_host: 127.0.0.1
          ansible_port: 2221
          nginx_server_name: nginx1.local
          nginx_instance_name: nginx-1
        nginx2:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          nginx_server_name: nginx2.local
          nginx_instance_name: nginx-2
  vars:
    ansible_connection: ssh
    ansible_user: ansible
    ansible_ssh_private_key_file: .ssh/ansible_lab
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
