{{- if .Values.networkPolicy.enabled }}
{{- if .Values.networkPolicy.defaultDenyIngress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  labels:
    {{- include "rbac-netpol-lab.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-to-db
  labels:
    {{- include "rbac-netpol-lab.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: app
      ports:
        - protocol: TCP
          port: {{ .Values.workloads.db.port }}
{{- end }}
