{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  labels:
    {{- include "rbac-netpol-lab.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.readonlyServiceAccount }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  labels:
    {{- include "rbac-netpol-lab.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.deployerServiceAccount }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
